export const STORE_USER_PROFILE = "STORE_USER_PROFILE";
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";
export const UPDATE_EMAIL_VERIFIED = "UPDATE_EMAIL_VERIFIED"
export const MAIL_SENT = "MAIL_SENT"