export const ppcpages = [
    {
        title: "aws-ccp",
        slug: "aws-certified-cloud-practitioner",
        type: "AWS",
        coursename: "AWS Certified Cloud Practitioner",
        benefits: [{ title: "This AWS Cloud Practitioner Certification is an opportunity to get recognized for your hard-earned AWS skills and also for those who would like to upgrade their knowledge on AWS platforms. By learning the exam objectives for the AWS CCP exam, you will be placed in a remarkable position in the journey of your AWS career." },
            "Deep Understanding about AWS Cloud Concepts", "Knowledge on Handling Security & Compliance in AWS environment",
            "Learning the Technologies in AWS Cloud Platform", "Compiling AWS Billing & Pricing"],
        realexam: { title: "AWS Certified Cloud Practitioner (CLF-C01)", prior_certification: "Not Required", exam_validity: "3 Years", exam_fees: "$100 USD", exam_duration: "90 minutes", no_of_question: "65",passing_mark:"65-70%", recomended_experience: "6 months exposure to the AWS cloud", exam_format: "Multiple choice & Select" },
        enroll: "No matter, whatever role you are playing in AWS as an entry-level,",
        enrollstrong: "this certification can definitely boost your career to an advanced level.",
        content_banner: "/images/ppcbanner4.webp",
        benefits_img:"/images/aws-cloud-img.webp",
        language:" English, French, German, Indonesian, Italian, Japanese, Korean, Portuguese, Simplified Chinese, and Spanish"
    }
    ,
    {
        title: "aws-devops",
        slug: "aws-devops-certification-training",
        type: "AWS",
        coursename: "AWS Certified DevOps Engineer Professional",
        benefits: [{ title: "This AWS Certified DevOps Engineer Professional Certification is an opportunity to get recognized for your hard-earned AWS skills and also for those who would like to upgrade their knowledge on AWS platforms. By learning the exam objectives for the AWS DevOps exam, you will be placed in a remarkable position in the journey of your AWS career." },
            "Deep Understanding about AWS DevOps Concepts", "Demonstrate DevOps skills such as operating, provisioning, managing distributed systems and applications, automating the testing and deployment of AWS infrastructure and applications ",
            "Learning the Technologies in AWS Cloud Platform", "Compiling AWS Billing & Pricing"],
        realexam: { title: "AWS Certified DevOps Engineer Professional (DOP-C01)", prior_certification: "Not Required", exam_validity: "3 Years", exam_fees: "$300 USD", exam_duration: "180 minutes", no_of_question: "75",passing_mark:"75-80%", recomended_experience: "2+ years of experience provisioning , Operating, and managing AWS environments ", exam_format: "Multiple choice & Select" },
        enroll: "No matter, whatever role you are playing in AWS as an Expert level ,",
        enrollstrong: "this certification can definitely boost your career to a Specialty level.",
        content_banner: "/images/ppcbanner3.webp",
        benefits_img:"/images/awsdepben.webp"
    },

    {
        title: "aws-csaa",
        type: "AWS",
        slug: "aws-solutions-architect-associate",
        coursename: "AWS Certified Solutions Architect Associate",
        benefits: [{ title: "This AWS Certified Solutions Architect Associate Certification is an opportunity to get recognized for your hard-earned AWS skills and also for those who would like to upgrade their knowledge on AWS platforms. By learning the exam objectives for the AWS CSAA exam, you will be placed in a remarkable position in the journey of your AWS career." },
            "Able to design architectures and demonstrate solutions on AWS for real-time business applications.", "Able to work on sophisticated projects at top companies such as Amazon, IBM, Infosys, Wipro, and so on.", "In demand and future-proof your architect career in the cloud environment.",
            "Getting a higher salary around $153,142 annually on average according to the Global Knowledge survey."],
        realexam: { title: "AWS Certified Solution Architect Associate (SAA-C02)", prior_certification: "Not Required", exam_validity: "3 Years", exam_fees: "$150 USD", exam_duration: "130 minutes", no_of_question: "60-70",passing_mark:"70-75%", recomended_experience: "At least 1Year of hands-on experience desigining securehigh performing, cost-effective and scalable systems on AWS" },
        enroll: "No matter, whatever role you are playing in AWS as an Associate level,",
        enrollstrong: "this certification can definitely boost your career to an Expert level. ",
        content_banner: "/images/ppcbanner2.webp",
        benefits_img:"/images/awscsaben.webp"
    },
    {
        title: "aws-cda",
        slug: "aws-developer-associate",
        type: "AWS",
        coursename: "AWS Certified Developer Associate",
        benefits: [{ title: "This AWS Certified Developer Associate Certification is an opportunity to get recognized for your hard-earned AWS skills and also for those who would like to upgrade their knowledge on AWS platforms. By learning the exam objectives for the AWS CDA exam, you will be placed in a remarkable position in the journey of your AWS career" },
            "Able to perform and demonstrate exceptional AWS development skills for real-time business applications.", "Able to get good opportunities from top companies such as Amazon, IBM, Infosys, Wipro, and so on.",
            "In demand and future-proof your career in cloud environment.", "Getting a higher salary around $159,767 on average according to Global Knowledge survey."],
        realexam: { title: "AWS certified Developer Associate (DVA-C01)", prior_certification: "Not Required", exam_validity: "3 Years", exam_fees: "$150 USD", exam_duration: "130 minutes", no_of_question: "65",passing_mark:"70-75%", recomended_experience: "1+ years of hands-on experience developing & maintaining on AWS-based application", exam_format: "Multiple choice & Select" },
        enroll: "No matter, whatever role you are playing in AWS as an Associate level,",
        enrollstrong: "this certification can definitely boost your career to a Expert level.",
        content_banner: "/images/ppcbanner1.webp",
        benefits_img:"/images/awscdaben.webp"
    },
    {
        title: "aws-sysops",
        slug: "aws-sysops-administrator-associate",
        type: "AWS",
        coursename: "AWS Certified SysOps Administrator Associate",
        benefits: [{ title: "This AWS Certified SysOps Administrator Associate Certification is an opportunity to get recognized for your hard-earned AWS skills and also for those who would like to upgrade their knowledge on AWS platforms. By learning the exam objectives for the AWS SysOps exam, you will be placed in a remarkable position in the journey of your AWS career." },
            "Implementation of AWS Monitoring, Logging & Remediation", "How to do Provisioning and Automation on Cloud resources",
            "Troubleshooting in Networks and seamless Content Delivery ", "Optimizing Cloud Cost and its Performance "],
        realexam: { title: "AWS Certified SysOps Adminstrator Associate (SOA-C02)", prior_certification: "Not Required", exam_validity: "3 Years", exam_fees: "$180 USD", exam_duration: "180 minutes", no_of_question: "65",passing_mark:"70-75%", recomended_experience: "At least 1 year of hands-on experience with AWS- deploying, managing and operating workloads", exam_format: "Multiple choice/Multiple Response/ Exam Lab" },
        enroll: "No matter, whatever role you are playing in AWS as an Associate level ,",
        enrollstrong: "this certification can definitely boost your career to a Expert level.",
        content_banner: "/images/ppcbanner4.webp",
        benefits_img:"/images/awssaaben.webp"
    },
    {
        title: "aws-csap",
        slug: "aws-solutions-architect-professional",
        type: "AWS",
        coursename: "AWS Certified Solutions Architect Professional",
        benefits: [{ title: "This AWS Certified Solutions Architect Professional Certification is an opportunity to get recognized for your hard-earned AWS skills and also for those who would like to upgrade their knowledge on AWS platforms. By learning the exam objectives for the AWS CSAP exam, you will be placed in a remarkable position in the journey of your AWS career." },
            "Deep Understanding about AWS Cloud Concepts", "Knowledge on Handling Security & Compliance in AWS environment ",
            "Learning the Technologies in AWS Cloud Platform", "Compiling AWS Billing & Pricing "],
        realexam: { title: "AWS Certified Solution Architect Professional (SAP-C01)", prior_certification: "Not Required", exam_validity: "3 Years", exam_fees: "$300 USD", exam_duration: "180 minutes", no_of_question: "75",passing_mark:"75-80%", recomended_experience: "2+ years of experience desigining & deploying cloud architecture on AWS", exam_format: "Multiple choice & Multiple Select" },
        enroll: "No matter, whatever role you are playing in AWS as an Expert level ,",
        enrollstrong: "this certification can definitely boost your career to a Specialty level.",
        content_banner: "/images/ppcbanner3.webp",
        benefits_img:"/images/awssapben.webp"
    },
    {
        title: "az-900",
        slug: "microsoft-azure-certification-az-900",
        type: "Azure",
        coursename: "Microsoft Azure Fundamentals (AZ-900)",
        benefits: [{ title: "This Microsoft Azure Fundamentals (AZ-900) Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure AZ-900 exam, you will be placed in a remarkable position in the journey of your Azure career." },
            "Deep Understanding about Azure Cloud Concepts", "Knowledge on technology concepts like Storage, Computing, Networking, and application development and support        ",
            "Learning the Technologies in Azure Cloud Services", "Compiling AWS Billing & Pricing "],
        realexam: { title: "AZ-900: Microsoft Azure Fundamentals", prior_certification: "Not Required", exam_validity: "LifeTime", exam_fees: "$99 USD", exam_duration: "90 minutes", no_of_question: "40-60",passing_mark:"700", recomended_experience: "Foundational knowledge of cloud Services and Azure Services", exam_format: "Multiple choice, Drag & Drop, Case studies,Multiple response" },
        enroll: "No matter, whatever role you are playing in Azure as an entry-level ,",
        enrollstrong: "this certification can definitely boost your career to an advanced level. ",
        content_banner: "/images/ppcbanner2.webp",
        benefits_img:"/images/msaz900ben.webp"
    },
    {
        title: "az-104",
        slug: "microsoft-azure-certification-az-104",
        type: "Azure",
        coursename: "Microsoft Azure Administrator (AZ-104) ",
        benefits: [{ title: "This Microsoft Azure Administrator (AZ-104) Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure AZ-104 exam, you will be placed in a remarkable position in the journey of your Azure career.        " },
            "Able to implement, manage, configure, monitor Azure services, virtual networks and demonstrate admin skills on Azure.", "Able to work with the team on various sophisticated Azure projects at top companies such as Microsoft, Accenture, Mercedes-Benz, Randstad, Wipro, and so on.            ",
            "In demand among the cloud administrators and future-proof your admin career in the cloud environment.", "Receive exceptional opportunities and salaries."],
        realexam: { title: "AZ-104: Microsoft Azure Administrator", prior_certification: "Not Required", exam_validity: "1 Year", exam_fees: "$165 USD", exam_duration: "150 minutes", no_of_question: "40-60",passing_mark:"700", recomended_experience: "6+ months of hands-on experience administering Azure; Strong understanding of core Azure Services, Azure Workloads, Security and Governance", exam_format: "Multiple choice, Drag & Drop, Case studies,Multiple response" },
        enroll: "No matter, whatever role you are playing in Azure as an Associate-level ,",
        enrollstrong: "this certification can definitely boost your career to an Expert level. ",
        content_banner: "/images/ppcbanner1.webp",
        benefits_img:"/images/msaz104ben.webp"
    },
    {
        title: "az-305",
        slug: "designing-microsoft-azure-infrastructure-solutions-az-305",
        type: "Azure",
        coursename: "Designing Microsoft Azure Infrastructure Solutions (AZ-305)",
        benefits: [{ title: "This Designing Microsoft Azure Infrastructure Solutions (AZ-305) Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure AZ-305 exam, you will be placed in a remarkable position in the journey of your Azure career.        " },
            "Able to implement, Manage Azure Active Directory, Cloud migration to Azure strategy, Configure serverless computing with Azure, Integration of on-prem infrastructure, and Configure Azure Kubernetes Service (AKS) skills on Azure.  ", "Able to work with the team on various sophisticated Azure projects at top companies such as Microsoft, Accenture, Mercedes-Benz, Randstad, Wipro, and so on.",
            "In demand among the cloud administrators and future-proof your admin career in the cloud environment.", "Receive exceptional opportunities and salaries."],
        realexam: { title: "Designing Microsoft Azure Infrastructure Solutions:Exam AZ-305", prior_certification: "Not Required", exam_validity: "1 Year", exam_fees: "$165 USD", exam_duration: "120 minutes", no_of_question: "110",passing_mark:"", recomended_experience: "Advanced experience and knowledge of IT operations, including networking, virtualization, identity, security, business continuity, disaster recovery, data platforms, and governance.", exam_format: "Multiple choice, Drag & Drop, Case studies,Multiple response" },
        enroll: "No matter, whatever role you are playing in Azure as an Associate-level ,",
        enrollstrong: "this certification can definitely boost your career to an Expert level. ",
        content_banner: "/images/ppcbanner4.webp",
        benefits_img:"/images/msaz305ben.webp"
    },
    {
        title: "az-204",
        slug: "microsoft-azure-certification-az-104",
        type: "Azure",
        coursename: "Developing Solutions for Microsoft Azure (AZ-204)",
        benefits: [{ title: "This Developing Solutions for Microsoft Azure (AZ-204)Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure AZ-204 exam, you will be placed in a remarkable position in the journey of your Azure career.        " },
            "Able to develop, deploy and maintain solutions and demonstrate applications on Azure.", "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on. ",
            "In demand and future-proof your architect career in the cloud environment. ", "Receive good opportunities and a competitive salary. "],
        realexam: { title: "AZ-204: Developing Solution for Microsoft Azure", prior_certification: "Not Required", exam_validity: "1 Year", exam_fees: "$165 USD", exam_duration: "150 minutes", no_of_question: "40-60", passing_mark:"70%",recomended_experience: "1-2 Years of professional development experience and experience with Microsoft Azure", exam_format: "Multiple choice, Drag & Drop, Case studies,Multiple response" },
        enroll: "No matter, whatever role you are playing in Azure as an Associate-level ,",
        enrollstrong: " this certification can definitely boost your career to an Expert level.  ",
        content_banner: "/images/ppcbanner3.webp",
        benefits_img:"/images/msaz204ben.webp"
    },
    {
        title: "az-400",
        slug: "microsoft-azure-certification-az-400",
        type: "Azure",
        coursename: "Designing and Implementing Microsoft DevOps Solutions (AZ-400)        ",
        benefits: [{ title: "This Designing and Implementing Microsoft DevOps Solutions (AZ-400) Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure AZ-400 exam, you will be placed in a remarkable position in the journey of your Azure career.        " },
            "Designing and implementing strategies for collaboration, code, infrastructure, source control, security, compliance, continuous integration, testing, delivery, monitoring, and feedback are among the responsibilities you need to have in this position.            ", "In demand and future-proof your architect career in the cloud environment.            ",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "AZ-400: Desigining and Implementing Microsoft DevOps Solution", prior_certification: "Must have AZ-104 or AZ-204", exam_validity: "1 Year", exam_fees: "$165 USD", exam_duration: "150 minutes", no_of_question: "40-60", passing_mark:"700", recomended_experience: "Knowledge in both Azure administration and edevelopment with expertise in at least one of these areas ", exam_format: "Multiple choice, Drag & Drop, Case studies,Multiple response" },
        enroll: "No matter, whatever role you are playing in Azure as an Expert-level,",
        enrollstrong: " this certification can definitely boost your career to a Specialty level.",
        content_banner: "/images/ppcbanner2.webp",
        benefits_img:"/images/msaz400ben.webp"
    },
    {
        title: "dp-203",
        slug: "microsoft-azure-certification-dp-203",
        type: "Azure",
        coursename: "Data Engineering on Microsoft Azure (DP-203)",
        benefits: [{ title: "This Data Engineering on Microsoft Azure (DP-203) Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure DP-203 exam, you will be placed in a remarkable position in the journey of your Azure career.        " },
            "Designing and Implementing data storage and data security.", "In demand and future-proof your architect career in the cloud environment.",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "DP-203: Data Engineering on Microsoft Azure", prior_certification: "", exam_validity: "1 Year", exam_fees: "$165 USD", exam_duration: "180 minutes", no_of_question: "40-60", passing_mark:"70%", recomended_experience: "", exam_format: "Multiple choice Questions" },
        enroll: "No matter, whatever role you are playing in Azure as an Associate-level ,",
        enrollstrong: "  this certification can definitely boost your career to an Expert level.",
        content_banner: "/images/ppcbanner1.webp",
        benefits_img:"/images/msdp203ben.webp"
    },
    {
        title: "gccace",
        slug: "google-cloud-certified-associate-cloud-engineer",
        type: "Google",
        coursename: "Google Cloud Certified Associate Cloud Engineer",
        benefits: [{ title: "This Google Cloud Certified Associate Cloud Engineer Certification is an opportunity to get recognized for your hard-earned GCP skills and also for those who would like to upgrade their knowledge on Google platforms. By learning the exam objectives for the Google Cloud Certified Associate Cloud Engineer exam, you will be placed in a remarkable position in the journey of your GCP career." },
            "Deep Understanding about GCP Cloud Engineering Concepts", "Knowledge of deploying applications, monitoring operations, and managing enterprise solutions",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "Google Cloud Certified Associate Cloud Engineer", prior_certification: "Not Required", exam_validity: "2 Year", exam_fees: "$125 USD", exam_duration: "120 minutes", no_of_question: "50(Approx)", passing_mark:"70% (Approx)", recomended_experience: "6+ months hands-on experience with Google Cloud", exam_format: "Multiple choice Questions & Multiple Select" },
        enroll: "No matter, whatever role you are playing in GCP as an Associate-level ,",
        enrollstrong: "this certification can definitely boost your career to an Expert level.",
        content_banner: "/images/ppcbanner4.webp",
        benefits_img:"/images/googleaceben.webp"
    },
    {
        title: "gccpca",
        slug: "google-cloud-certified-professional-cloud-architect",
        type: "Google",
        coursename: "Google Cloud Certified Professional Cloud Architect",
        benefits: [{ title: "This Google Cloud Certified Professional Cloud Architect Certification is an opportunity to get recognized for your hard-earned GCP skills and also for those who would like to upgrade their knowledge on Google platforms. By learning the exam objectives for the Google Cloud Certified Professional Cloud Architect exam, you will be placed in a remarkable position in the journey of your GCP career." },
            "Deep Understanding about GCP Cloud Cloud Architect Concepts", "Knowledge of GCP services, management tools, compute service, security, and many other advanced topics",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "Google Cloud Certified Professional Cloud Architect", prior_certification: "Not Required", exam_validity: "2 Year", exam_fees: "$200 USD", exam_duration: "120 minutes", no_of_question: "50(Approx)", passing_mark:"80% (Approx)", recomended_experience: "3+ years of industry experience, 1+ years desigining & mamaning solutions on Google Cloud", exam_format: "Multiple choice Questions & Multiple Select" },
        enroll: "No matter, whatever role you are playing in GCP as an Expert-level ,",
        enrollstrong: "this certification can definitely boost your career to an Advance level.",
        content_banner: "/images/ppcbanner3.webp",
        benefits_img:"/images/googlepceben.webp"
    },
    {
        title: "gcccdl",
        slug: "google-cloud-certified-professional-cloud-architect",
        type: "Google",
        coursename: "Google Cloud Certified Cloud Digital Leader ",
        benefits: [{ title: "This Google Cloud Certified Cloud Digital Leader Certification is an opportunity to get recognized for your hard-earned GCP skills and also for those who would like to upgrade their knowledge on Google platforms. By learning the exam objectives for the Google Cloud Certified Cloud Digital Leader exam, you will be placed in a remarkable position in the journey of your GCP career." },
            "Deep Understanding about GCP Cloud Fundamentals Concepts", "GCP Cloud Digital Leader certification sets you on the certification path. This is your first step in becoming a GCP Cloud Expert.",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "Google Cloud Certified Cloud Digital Leader ", prior_certification: "Not Required", exam_validity: "2 Year", exam_fees: "$99 USD", exam_duration: "90 minutes", no_of_question: "50-60", passing_mark:"70% (Approx)", recomended_experience: "Collaorating with technical professional", exam_format: "Multiple Choice & Multiple Select" },
        enroll: "No matter, whatever role you are playing in GCP as an entry-level,",
        enrollstrong: "this certification can definitely boost your career to an Expert level.",
        content_banner: "/images/ppcbanner2.webp",
        benefits_img:"/images/googledlben.webp"
    },
    {
        title: "gccpde",
        slug: "google-cloud-certified-professional-data-engineer",
        type: "Google",
        coursename: "Google Cloud Certified Professional Data Engineer",
        benefits: [{ title: "This Google Cloud Certified Professional Data Engineer Certification is an opportunity to get recognized for your hard-earned GCP skills and also for those who would like to upgrade their knowledge on Google platforms. By learning the exam objectives for the Google Cloud Certified Professional Data Engineer exam, you will be placed in a remarkable position in the journey of your GCP career." },
            "Deep Understanding about GCP Cloud Fundamentals Concepts", "Implement decision-making functions for real-time applications by collecting, transforming, and publishing data",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "Google Cloud Certified Professional Data Engineer", prior_certification: "Not Required", exam_validity: "2 Year", exam_fees: "$200 USD", exam_duration: "120 minutes", no_of_question: "50(Approx)", passing_mark:"80% (Approx)", recomended_experience: "3+ years of industry experience- 1+ years desigining & managing solutions on Googlee cloud", exam_format: "Multiple Choice & Multiple Select" },
        enroll: "No matter, whatever role you are playing in GCP as an Expert-level,",
        enrollstrong: "this certification can definitely boost your career to an Advance level.",
        content_banner: "/images/ppcbanner1.webp",
        benefits_img:"/images/googlepdeben.webp"
    },
    {
        title: "sfscc",
        slug: "snowflake-snowpro-core-certification",
        type: "Snowflake",
        coursename: "Snowflake SnowPro Core Certification",
        benefits: [{ title: "The Snowflake SnowPro Core Certification is an entry-level certification exam from Snowflake. As the name suggests the main goal of this certification is to provide you with the necessary knowledge and skills to apply specific core Snowflake expertise while implementing and migrating. It is an essential certification for Snowflake which is one of the popular cloud data warehouses." },
            "Deep Understanding about Snowflake Fundamentals Concepts", "This SnowPro certification exam validates your skills such as designing, developing, and managing secure, scalable Snowflake solutions to meet business objectives. ",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "Snowflake SnowPro Core Certification", prior_certification: "Not Required", exam_validity: "2 Year", exam_fees: "$175 USD", exam_duration: "115 minutes", no_of_question: "100", passing_mark:"750+ (On a scale of 0-1000)", recomended_experience: "Basic knowledge of the snowflake platform", exam_format: "Multiple Choice ,Multiple Select,True/False" },
        enroll: "No matter, whatever role you are playing in GCP as an Expert-level,",
        enrollstrong: "this certification can definitely boost your career to an Advance level."
    },
    {
        title: "hccta",
        slug: "hashicorp-certified-terraform-associate",
        type: "HashiCorp",
        coursename: "HashiCorp Certified Terraform Associate Certification",
        benefits: [{ title: "The HashiCorp Certified Terraform Associate Certification is an entry-level certification exam from Snowflake. As the name suggests the main goal of this certification is to provide you with the necessary knowledge and skills to apply specific core Snowflake expertise while implementing and migrating. It is an essential certification for Snowflake which is one of the popular cloud data warehouses." },
            "Deep Understanding about Hashicorp Fundamentals Concepts", "This Hashicorp certification exam validates your skills such as designing, developing, and managing secure, scalable Snowflake solutions to meet business objectives. ",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "Snowflake SnowPro Core Certification", prior_certification: "Not Required", exam_validity: "2 Year", exam_fees: "$175 USD", exam_duration: "115 minutes", no_of_question: "100", passing_mark:"750+ (On a scale of 0-1000)", recomended_experience: "Basic knowledge of the snowflake platform", exam_format: "Multiple Choice ,Multiple Select,True/False" },
        enroll: "No matter, whatever role you are playing in GCP as an Expert-level,",
        enrollstrong: "this certification can definitely boost your career to an Advance level."
    },
    {
        title: "hccva",
        slug: "hashicorp-certified-vault-associate",
        type: "HashiCorp",
        coursename: "HashiCorp Certified Vault Associate",
        benefits: [{ title: "As we know, this is one of the most sought-after certifications by many cloud security professionals. The HashiCorp Vault certifications provide you with the essential skills for securing a multi-cloud environment and protecting sensitive data. With this knowledge, credibility, and skillset you can get opportunities to work for security divisions of large enterprises." },
            "Deep Understanding about Hashicorp Fundamentals Concepts", "This Hashicorp certification exam validates your skills such as designing, developing, and managing secure, scalable Snowflake solutions to meet business objectives. ",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "HashiCorp Certified: Vault Associate", prior_certification: "Not Required", exam_validity: "2 Year", exam_fees: "$70.50 USD", exam_duration: "60 minutes", no_of_question: "55-60", passing_mark:"70% or above", recomended_experience: "0-6 months of vault experience", exam_format: "Multiple Choice " },
        enroll: "No matter, whatever role you are playing in GCP as an Expert-level,",
        enrollstrong: "this certification can definitely boost your career to an Advance level."
    },
    {
        title: "hccca",
        slug: "hashicorp-certified-consul-associate",
        type: "HashiCorp",
        coursename: "HashiCorp Certified Consul Associate",
        benefits: [{ title: "As we know, this is one of the most sought-after certifications by many cloud security professionals. The HashiCorp Vault certifications provide you with the essential skills for securing a multi-cloud environment and protecting sensitive data. With this knowledge, credibility, and skillset you can get opportunities to work for security divisions of large enterprises." },
            "Deep Understanding about Hashicorp Fundamentals Concepts", "This Hashicorp certification exam validates your skills such as designing, developing, and managing secure, scalable Snowflake solutions to meet business objectives. ",
            "Able to work on complex cloud solution development projects at top companies such as Microsoft, IBM, Infosys, Wipro, TCS, Cognizant, and so on.", "Receive good opportunities and a competitive salary."],
        realexam: { title: "HashiCorp Certified Consul Associate", prior_certification: "Not Required", exam_validity: "2 Year", exam_fees: "$70.50 USD", exam_duration: "60 minutes", no_of_question: "120", passing_mark:"70% or above", recomended_experience: "Basic knowledge to build , secure and maintain open source HashiCorp consul", exam_format: "Multiple Choice " },
        enroll: "No matter, whatever role you are playing in GCP as an Expert-level,",
        enrollstrong: "this certification can definitely boost your career to an Advance level."
    },
    {
        title: "dp-900",
        slug: "microsoft-azure-certification-dp-900",
        type: "Azure",
        coursename: "Microsoft Azure Data Fundamentals ( DP-900 )",
        benefits: [{ title: "This Microsoft Azure Data Fundamentals ( DP-900 ) Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure DP-900 exam, you will be placed in a remarkable position in the journey of your Azure career." },
            "Deep Understanding about Azure Cloud Concepts", "The fundamentals of database concepts in a cloud environment, basic skilling in cloud data services, and cloud data services within Microsoft Azure.",
            "Processing options for building data analytics solutions in Azure. You will explore Azure Synapse Analytics, Azure Databricks, and Azure HDInsight. ", "Compiling Azure Billing & Pricing"],
        realexam: { title: "DP-900: Microsoft Azure Data Fundamentals", prior_certification: "Not Required", exam_validity: "Lifetime", exam_fees: "$99 USD", exam_duration: "90 minutes", no_of_question: "40-60", passing_mark:"700",recomended_experience: "Foundational Knowledge of core data concepts and their implementation in Microsoft Azure", exam_format: "Multiple choice, Drag & Drop, Case studies,Multiple response" },
        enroll: "No matter, whatever role you are playing in Azure as an entry-level,",
        enrollstrong: " this certification can definitely boost your career to an advanced level.",
        content_banner: "/images/ppcbanner3.webp",
        benefits_img:"/images/dp-900ben.png"
    },
    {
        title: "ai-900",
        slug: "microsoft-azure-certification-ai-900",
        type: "Azure",
        coursename: "Microsoft Azure AI Fundamentals ( AI-900 )",
        benefits: [{ title: "This Microsoft Azure AI Fundamentals ( AI-900 ) Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure AI-900 exam, you will be placed in a remarkable position in the journey of your Azure career." },
            "Deep Understanding about Azure Cloud Concepts", "You will learn about the types of solutions AI makes possible, and the services on Microsoft Azure that you can use to create them.",
            "Describe features of Natural Language Processing (NLP) workloads on Azure", "Compiling Azure Billing & Pricing"],
        realexam: { title: "AI-900: Microsoft Azure AI Fundamentals", prior_certification: "Not Required", exam_validity: "Lifetime", exam_fees: "$99 USD", exam_duration: "90 minutes", no_of_question: "40-60", passing_mark:"700",recomended_experience: "Foundational Knowledge of machine learning, artificial intelligence concepts and related Microsoft Azure services", exam_format: "Multiple choice, Drag & Drop, Case studies,Multiple response" },
        enroll: "No matter, whatever role you are playing in Azure as an entry-level",
        enrollstrong: "this certification can definitely boost your career to an advanced level.",
        content_banner: "/images/ppcbanner2.webp",
        benefits_img:"/images/ai-900ben.png"
    },
    {
        title: "sc-900",
        slug: "microsoft-security-compliance-identity-fundamentals-sc-900-certification",
        type: "Azure",
        coursename: "Microsoft Security, Compliance, and Identity Fundamentals ( SC-900 ) ",
        benefits: [{ title: "This Microsoft Security, Compliance, and Identity Fundamentals ( SC-900 ) Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure SC-900 exam, you will be placed in a remarkable position in the journey of your Azure career." },
            "Deep Understanding about Azure Cloud Concepts", "Familiar with Microsoft Azure and Microsoft 365 and want to understand how Microsoft security, compliance, and identity solutions can span across these solution areas to provide a holistic and end-to-end solution",
            "Learning the Technologies in Azure Cloud Services ", "Compiling Azure Billing & Pricing"],
        realexam: { title: "SC-900: Microsoft Security, compliance , and Identity Fundamentals ", prior_certification: "Not Required", exam_validity: "Lifetime", exam_fees: "$99 USD", exam_duration: "180 minutes", no_of_question: "110 questions", passing_mark:"700",recomended_experience: "Familiarity with Microsoft Azure and Microsoft 365", exam_format: "Multiple choice, Drag & Drop, Case studies,Multiple response" },
        enroll: "No matter, whatever role you are playing in Azure as an entry-level",
        enrollstrong: " this certification can definitely boost your career to an advanced level.",
        content_banner: "/images/ppcbanner1.webp",
        benefits_img:"/images/sc-900ben.png"
    },
    {
        title: "ai-102",
        slug: "microsoft-azure-certification-ai-102",
        type: "Azure",
        coursename: "Designing and Implementing a Microsoft Azure AI Solution ( AI-102 )",
        benefits: [{ title: "This Designing and Implementing a Microsoft Azure AI Solution (AI-102)  Certification is an opportunity to get recognized for your hard-earned Azure skills and also for those who would like to upgrade their knowledge on Azure platforms. By learning the exam objectives for the Azure AI-102 exam, you will be placed in a remarkable position in the journey of your Azure career." },
            "Create, configure, deploy, and secure Azure Cognitive Services.", "Develop applications that detect, analyze, and recognize faces",
            "Imbibe skills to create AI infused applications that leverage Azure Cognitive Services, Azure Cognitive Search, and Microsoft Bot Framework", "Receive exceptional opportunities and salaries."],
        realexam: { title: "AI-102: Desigining and Implementing a microsoft Azure AI Solution", prior_certification: "Not Required", exam_validity: "1 Year ", exam_fees: "$165 USD", exam_duration: "180 minutes", no_of_question: "40-60 questions", passing_mark:"700",recomended_experience: "Skills to build, manage and deploy AI solutions that leverage Azure Cognitive Services and Azure Applied AI services", exam_format: "Multiple choice, Drag & Drop, Case studies,Multiple response" },
        enroll: "No matter, whatever role you are playing in Azure as an Associate-level",
        enrollstrong: " this certification can definitely boost your career to an Expert level.",
        content_banner: "/images/ppcbanner4.webp",
        benefits_img:"/images/ai-102ben.png"
    },
];